package com.stock.dao.mapper.sys;

import com.stock.dao.model.sys.SysAttachment;
import com.stock.dao.model.sys.SysAttachmentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysAttachmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_attachment
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    int countByExample(SysAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_attachment
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    int deleteByExample(SysAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_attachment
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    int deleteByPrimaryKey(Integer attachmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_attachment
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    int insert(SysAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_attachment
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    int insertSelective(SysAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_attachment
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    List<SysAttachment> selectByExample(SysAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_attachment
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    SysAttachment selectByPrimaryKey(Integer attachmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_attachment
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") SysAttachment record, @Param("example") SysAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_attachment
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    int updateByExample(@Param("record") SysAttachment record, @Param("example") SysAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_attachment
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    int updateByPrimaryKeySelective(SysAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_attachment
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    int updateByPrimaryKey(SysAttachment record);
}