package com.stock.dao.mapper.sys;

import com.stock.dao.model.sys.SysBasicDataSet;
import com.stock.dao.model.sys.SysBasicDataSetExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysBasicDataSetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_basic_data_set
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    int countByExample(SysBasicDataSetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_basic_data_set
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    int deleteByExample(SysBasicDataSetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_basic_data_set
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    int deleteByPrimaryKey(Integer basicDataSetId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_basic_data_set
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    int insert(SysBasicDataSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_basic_data_set
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    int insertSelective(SysBasicDataSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_basic_data_set
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    List<SysBasicDataSet> selectByExample(SysBasicDataSetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_basic_data_set
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    SysBasicDataSet selectByPrimaryKey(Integer basicDataSetId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_basic_data_set
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") SysBasicDataSet record, @Param("example") SysBasicDataSetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_basic_data_set
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    int updateByExample(@Param("record") SysBasicDataSet record, @Param("example") SysBasicDataSetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_basic_data_set
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    int updateByPrimaryKeySelective(SysBasicDataSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_basic_data_set
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    int updateByPrimaryKey(SysBasicDataSet record);
}