package com.stock.dao.mapper.sys;

import com.stock.dao.model.sys.SysOrganizationStructure;
import com.stock.dao.model.sys.SysOrganizationStructureExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysOrganizationStructureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization_structure
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    int countByExample(SysOrganizationStructureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization_structure
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    int deleteByExample(SysOrganizationStructureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization_structure
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    int deleteByPrimaryKey(Integer organizationStructureId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization_structure
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    int insert(SysOrganizationStructure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization_structure
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    int insertSelective(SysOrganizationStructure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization_structure
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    List<SysOrganizationStructure> selectByExample(SysOrganizationStructureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization_structure
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    SysOrganizationStructure selectByPrimaryKey(Integer organizationStructureId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization_structure
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") SysOrganizationStructure record, @Param("example") SysOrganizationStructureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization_structure
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    int updateByExample(@Param("record") SysOrganizationStructure record, @Param("example") SysOrganizationStructureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization_structure
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    int updateByPrimaryKeySelective(SysOrganizationStructure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization_structure
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    int updateByPrimaryKey(SysOrganizationStructure record);
}