package com.stock.dao.model.sys;

import java.io.Serializable;
import java.util.Date;

public class SysAttachment implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_attachment.attachment_id
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private Integer attachmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_attachment.business_table
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private String businessTable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_attachment.business_id
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private Integer businessId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_attachment.attachment_name
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private String attachmentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_attachment.attachment_path
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private String attachmentPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_attachment.title
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_attachment.size
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private String size;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_attachment.document_type
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private String documentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_attachment.download_number
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private Integer downloadNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_attachment.is_choose
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private Byte isChoose;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_attachment.remarks
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_attachment.description
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_attachment.creator
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private Integer creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_attachment.create_time
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_attachment.amender
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private Integer amender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_attachment.amend_time
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private Date amendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_attachment.record_version
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private Integer recordVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_attachment.is_deleted
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private Integer isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_attachment
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_attachment.attachment_id
     *
     * @return the value of sys_attachment.attachment_id
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public Integer getAttachmentId() {
        return attachmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_attachment.attachment_id
     *
     * @param attachmentId the value for sys_attachment.attachment_id
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setAttachmentId(Integer attachmentId) {
        this.attachmentId = attachmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_attachment.business_table
     *
     * @return the value of sys_attachment.business_table
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public String getBusinessTable() {
        return businessTable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_attachment.business_table
     *
     * @param businessTable the value for sys_attachment.business_table
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setBusinessTable(String businessTable) {
        this.businessTable = businessTable == null ? null : businessTable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_attachment.business_id
     *
     * @return the value of sys_attachment.business_id
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public Integer getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_attachment.business_id
     *
     * @param businessId the value for sys_attachment.business_id
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setBusinessId(Integer businessId) {
        this.businessId = businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_attachment.attachment_name
     *
     * @return the value of sys_attachment.attachment_name
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public String getAttachmentName() {
        return attachmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_attachment.attachment_name
     *
     * @param attachmentName the value for sys_attachment.attachment_name
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setAttachmentName(String attachmentName) {
        this.attachmentName = attachmentName == null ? null : attachmentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_attachment.attachment_path
     *
     * @return the value of sys_attachment.attachment_path
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public String getAttachmentPath() {
        return attachmentPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_attachment.attachment_path
     *
     * @param attachmentPath the value for sys_attachment.attachment_path
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setAttachmentPath(String attachmentPath) {
        this.attachmentPath = attachmentPath == null ? null : attachmentPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_attachment.title
     *
     * @return the value of sys_attachment.title
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_attachment.title
     *
     * @param title the value for sys_attachment.title
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_attachment.size
     *
     * @return the value of sys_attachment.size
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public String getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_attachment.size
     *
     * @param size the value for sys_attachment.size
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setSize(String size) {
        this.size = size == null ? null : size.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_attachment.document_type
     *
     * @return the value of sys_attachment.document_type
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public String getDocumentType() {
        return documentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_attachment.document_type
     *
     * @param documentType the value for sys_attachment.document_type
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setDocumentType(String documentType) {
        this.documentType = documentType == null ? null : documentType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_attachment.download_number
     *
     * @return the value of sys_attachment.download_number
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public Integer getDownloadNumber() {
        return downloadNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_attachment.download_number
     *
     * @param downloadNumber the value for sys_attachment.download_number
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setDownloadNumber(Integer downloadNumber) {
        this.downloadNumber = downloadNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_attachment.is_choose
     *
     * @return the value of sys_attachment.is_choose
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public Byte getIsChoose() {
        return isChoose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_attachment.is_choose
     *
     * @param isChoose the value for sys_attachment.is_choose
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setIsChoose(Byte isChoose) {
        this.isChoose = isChoose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_attachment.remarks
     *
     * @return the value of sys_attachment.remarks
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_attachment.remarks
     *
     * @param remarks the value for sys_attachment.remarks
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_attachment.description
     *
     * @return the value of sys_attachment.description
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_attachment.description
     *
     * @param description the value for sys_attachment.description
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_attachment.creator
     *
     * @return the value of sys_attachment.creator
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_attachment.creator
     *
     * @param creator the value for sys_attachment.creator
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_attachment.create_time
     *
     * @return the value of sys_attachment.create_time
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_attachment.create_time
     *
     * @param createTime the value for sys_attachment.create_time
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_attachment.amender
     *
     * @return the value of sys_attachment.amender
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public Integer getAmender() {
        return amender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_attachment.amender
     *
     * @param amender the value for sys_attachment.amender
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setAmender(Integer amender) {
        this.amender = amender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_attachment.amend_time
     *
     * @return the value of sys_attachment.amend_time
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public Date getAmendTime() {
        return amendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_attachment.amend_time
     *
     * @param amendTime the value for sys_attachment.amend_time
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setAmendTime(Date amendTime) {
        this.amendTime = amendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_attachment.record_version
     *
     * @return the value of sys_attachment.record_version
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public Integer getRecordVersion() {
        return recordVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_attachment.record_version
     *
     * @param recordVersion the value for sys_attachment.record_version
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setRecordVersion(Integer recordVersion) {
        this.recordVersion = recordVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_attachment.is_deleted
     *
     * @return the value of sys_attachment.is_deleted
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_attachment.is_deleted
     *
     * @param isDeleted the value for sys_attachment.is_deleted
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_attachment
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SysAttachment other = (SysAttachment) that;
        return (this.getAttachmentId() == null ? other.getAttachmentId() == null : this.getAttachmentId().equals(other.getAttachmentId()))
            && (this.getBusinessTable() == null ? other.getBusinessTable() == null : this.getBusinessTable().equals(other.getBusinessTable()))
            && (this.getBusinessId() == null ? other.getBusinessId() == null : this.getBusinessId().equals(other.getBusinessId()))
            && (this.getAttachmentName() == null ? other.getAttachmentName() == null : this.getAttachmentName().equals(other.getAttachmentName()))
            && (this.getAttachmentPath() == null ? other.getAttachmentPath() == null : this.getAttachmentPath().equals(other.getAttachmentPath()))
            && (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
            && (this.getSize() == null ? other.getSize() == null : this.getSize().equals(other.getSize()))
            && (this.getDocumentType() == null ? other.getDocumentType() == null : this.getDocumentType().equals(other.getDocumentType()))
            && (this.getDownloadNumber() == null ? other.getDownloadNumber() == null : this.getDownloadNumber().equals(other.getDownloadNumber()))
            && (this.getIsChoose() == null ? other.getIsChoose() == null : this.getIsChoose().equals(other.getIsChoose()))
            && (this.getRemarks() == null ? other.getRemarks() == null : this.getRemarks().equals(other.getRemarks()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getCreator() == null ? other.getCreator() == null : this.getCreator().equals(other.getCreator()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getAmender() == null ? other.getAmender() == null : this.getAmender().equals(other.getAmender()))
            && (this.getAmendTime() == null ? other.getAmendTime() == null : this.getAmendTime().equals(other.getAmendTime()))
            && (this.getRecordVersion() == null ? other.getRecordVersion() == null : this.getRecordVersion().equals(other.getRecordVersion()))
            && (this.getIsDeleted() == null ? other.getIsDeleted() == null : this.getIsDeleted().equals(other.getIsDeleted()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_attachment
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAttachmentId() == null) ? 0 : getAttachmentId().hashCode());
        result = prime * result + ((getBusinessTable() == null) ? 0 : getBusinessTable().hashCode());
        result = prime * result + ((getBusinessId() == null) ? 0 : getBusinessId().hashCode());
        result = prime * result + ((getAttachmentName() == null) ? 0 : getAttachmentName().hashCode());
        result = prime * result + ((getAttachmentPath() == null) ? 0 : getAttachmentPath().hashCode());
        result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
        result = prime * result + ((getSize() == null) ? 0 : getSize().hashCode());
        result = prime * result + ((getDocumentType() == null) ? 0 : getDocumentType().hashCode());
        result = prime * result + ((getDownloadNumber() == null) ? 0 : getDownloadNumber().hashCode());
        result = prime * result + ((getIsChoose() == null) ? 0 : getIsChoose().hashCode());
        result = prime * result + ((getRemarks() == null) ? 0 : getRemarks().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getCreator() == null) ? 0 : getCreator().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getAmender() == null) ? 0 : getAmender().hashCode());
        result = prime * result + ((getAmendTime() == null) ? 0 : getAmendTime().hashCode());
        result = prime * result + ((getRecordVersion() == null) ? 0 : getRecordVersion().hashCode());
        result = prime * result + ((getIsDeleted() == null) ? 0 : getIsDeleted().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_attachment
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", attachmentId=").append(attachmentId);
        sb.append(", businessTable=").append(businessTable);
        sb.append(", businessId=").append(businessId);
        sb.append(", attachmentName=").append(attachmentName);
        sb.append(", attachmentPath=").append(attachmentPath);
        sb.append(", title=").append(title);
        sb.append(", size=").append(size);
        sb.append(", documentType=").append(documentType);
        sb.append(", downloadNumber=").append(downloadNumber);
        sb.append(", isChoose=").append(isChoose);
        sb.append(", remarks=").append(remarks);
        sb.append(", description=").append(description);
        sb.append(", creator=").append(creator);
        sb.append(", createTime=").append(createTime);
        sb.append(", amender=").append(amender);
        sb.append(", amendTime=").append(amendTime);
        sb.append(", recordVersion=").append(recordVersion);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}