package com.stock.dao.model.sys;

import java.io.Serializable;

public class SysLogWithBLOBs extends SysLog implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.log_parameters
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private String logParameters;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.log_message
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private String logMessage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_log
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.log_parameters
     *
     * @return the value of sys_log.log_parameters
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public String getLogParameters() {
        return logParameters;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.log_parameters
     *
     * @param logParameters the value for sys_log.log_parameters
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setLogParameters(String logParameters) {
        this.logParameters = logParameters == null ? null : logParameters.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.log_message
     *
     * @return the value of sys_log.log_message
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public String getLogMessage() {
        return logMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.log_message
     *
     * @param logMessage the value for sys_log.log_message
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setLogMessage(String logMessage) {
        this.logMessage = logMessage == null ? null : logMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SysLogWithBLOBs other = (SysLogWithBLOBs) that;
        return (this.getLogId() == null ? other.getLogId() == null : this.getLogId().equals(other.getLogId()))
            && (this.getLogTime() == null ? other.getLogTime() == null : this.getLogTime().equals(other.getLogTime()))
            && (this.getLogType() == null ? other.getLogType() == null : this.getLogType().equals(other.getLogType()))
            && (this.getLogUserId() == null ? other.getLogUserId() == null : this.getLogUserId().equals(other.getLogUserId()))
            && (this.getLogUserIp() == null ? other.getLogUserIp() == null : this.getLogUserIp().equals(other.getLogUserIp()))
            && (this.getLogClass() == null ? other.getLogClass() == null : this.getLogClass().equals(other.getLogClass()))
            && (this.getLogFunction() == null ? other.getLogFunction() == null : this.getLogFunction().equals(other.getLogFunction()))
            && (this.getLogReturn() == null ? other.getLogReturn() == null : this.getLogReturn().equals(other.getLogReturn()))
            && (this.getLogStatus() == null ? other.getLogStatus() == null : this.getLogStatus().equals(other.getLogStatus()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getCreator() == null ? other.getCreator() == null : this.getCreator().equals(other.getCreator()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getAmender() == null ? other.getAmender() == null : this.getAmender().equals(other.getAmender()))
            && (this.getAmendTime() == null ? other.getAmendTime() == null : this.getAmendTime().equals(other.getAmendTime()))
            && (this.getAccessGroup() == null ? other.getAccessGroup() == null : this.getAccessGroup().equals(other.getAccessGroup()))
            && (this.getRecordVersion() == null ? other.getRecordVersion() == null : this.getRecordVersion().equals(other.getRecordVersion()))
            && (this.getIsDeleted() == null ? other.getIsDeleted() == null : this.getIsDeleted().equals(other.getIsDeleted()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getLogParameters() == null ? other.getLogParameters() == null : this.getLogParameters().equals(other.getLogParameters()))
            && (this.getLogMessage() == null ? other.getLogMessage() == null : this.getLogMessage().equals(other.getLogMessage()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getLogId() == null) ? 0 : getLogId().hashCode());
        result = prime * result + ((getLogTime() == null) ? 0 : getLogTime().hashCode());
        result = prime * result + ((getLogType() == null) ? 0 : getLogType().hashCode());
        result = prime * result + ((getLogUserId() == null) ? 0 : getLogUserId().hashCode());
        result = prime * result + ((getLogUserIp() == null) ? 0 : getLogUserIp().hashCode());
        result = prime * result + ((getLogClass() == null) ? 0 : getLogClass().hashCode());
        result = prime * result + ((getLogFunction() == null) ? 0 : getLogFunction().hashCode());
        result = prime * result + ((getLogReturn() == null) ? 0 : getLogReturn().hashCode());
        result = prime * result + ((getLogStatus() == null) ? 0 : getLogStatus().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getCreator() == null) ? 0 : getCreator().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getAmender() == null) ? 0 : getAmender().hashCode());
        result = prime * result + ((getAmendTime() == null) ? 0 : getAmendTime().hashCode());
        result = prime * result + ((getAccessGroup() == null) ? 0 : getAccessGroup().hashCode());
        result = prime * result + ((getRecordVersion() == null) ? 0 : getRecordVersion().hashCode());
        result = prime * result + ((getIsDeleted() == null) ? 0 : getIsDeleted().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getLogParameters() == null) ? 0 : getLogParameters().hashCode());
        result = prime * result + ((getLogMessage() == null) ? 0 : getLogMessage().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", logParameters=").append(logParameters);
        sb.append(", logMessage=").append(logMessage);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}