package com.stock.dao.model.sys;

import java.io.Serializable;
import java.util.Date;

public class SysMessage implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_message.message_id
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private Integer messageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_message.container
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private String container;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_message.producer
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private Integer producer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_message.consumer
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private Integer consumer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_message.priority
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private Integer priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_message.title
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_message.message
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private String message;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_message.time
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_message.read_num
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private Integer readNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_message.last_read_time
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private Integer lastReadTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_message.type
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_message.creator
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private Integer creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_message.create_time
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_message.amender
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private Integer amender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_message.amend_time
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private Date amendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_message.access_group
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private Integer accessGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_message.record_version
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private Integer recordVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_message.is_deleted
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private Integer isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_message
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_message.message_id
     *
     * @return the value of sys_message.message_id
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public Integer getMessageId() {
        return messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_message.message_id
     *
     * @param messageId the value for sys_message.message_id
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setMessageId(Integer messageId) {
        this.messageId = messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_message.container
     *
     * @return the value of sys_message.container
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public String getContainer() {
        return container;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_message.container
     *
     * @param container the value for sys_message.container
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setContainer(String container) {
        this.container = container == null ? null : container.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_message.producer
     *
     * @return the value of sys_message.producer
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public Integer getProducer() {
        return producer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_message.producer
     *
     * @param producer the value for sys_message.producer
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setProducer(Integer producer) {
        this.producer = producer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_message.consumer
     *
     * @return the value of sys_message.consumer
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public Integer getConsumer() {
        return consumer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_message.consumer
     *
     * @param consumer the value for sys_message.consumer
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setConsumer(Integer consumer) {
        this.consumer = consumer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_message.priority
     *
     * @return the value of sys_message.priority
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_message.priority
     *
     * @param priority the value for sys_message.priority
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_message.title
     *
     * @return the value of sys_message.title
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_message.title
     *
     * @param title the value for sys_message.title
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_message.message
     *
     * @return the value of sys_message.message
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_message.message
     *
     * @param message the value for sys_message.message
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_message.time
     *
     * @return the value of sys_message.time
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_message.time
     *
     * @param time the value for sys_message.time
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_message.read_num
     *
     * @return the value of sys_message.read_num
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public Integer getReadNum() {
        return readNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_message.read_num
     *
     * @param readNum the value for sys_message.read_num
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setReadNum(Integer readNum) {
        this.readNum = readNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_message.last_read_time
     *
     * @return the value of sys_message.last_read_time
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public Integer getLastReadTime() {
        return lastReadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_message.last_read_time
     *
     * @param lastReadTime the value for sys_message.last_read_time
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setLastReadTime(Integer lastReadTime) {
        this.lastReadTime = lastReadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_message.type
     *
     * @return the value of sys_message.type
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_message.type
     *
     * @param type the value for sys_message.type
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_message.creator
     *
     * @return the value of sys_message.creator
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_message.creator
     *
     * @param creator the value for sys_message.creator
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_message.create_time
     *
     * @return the value of sys_message.create_time
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_message.create_time
     *
     * @param createTime the value for sys_message.create_time
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_message.amender
     *
     * @return the value of sys_message.amender
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public Integer getAmender() {
        return amender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_message.amender
     *
     * @param amender the value for sys_message.amender
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setAmender(Integer amender) {
        this.amender = amender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_message.amend_time
     *
     * @return the value of sys_message.amend_time
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public Date getAmendTime() {
        return amendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_message.amend_time
     *
     * @param amendTime the value for sys_message.amend_time
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setAmendTime(Date amendTime) {
        this.amendTime = amendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_message.access_group
     *
     * @return the value of sys_message.access_group
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public Integer getAccessGroup() {
        return accessGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_message.access_group
     *
     * @param accessGroup the value for sys_message.access_group
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setAccessGroup(Integer accessGroup) {
        this.accessGroup = accessGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_message.record_version
     *
     * @return the value of sys_message.record_version
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public Integer getRecordVersion() {
        return recordVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_message.record_version
     *
     * @param recordVersion the value for sys_message.record_version
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setRecordVersion(Integer recordVersion) {
        this.recordVersion = recordVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_message.is_deleted
     *
     * @return the value of sys_message.is_deleted
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_message.is_deleted
     *
     * @param isDeleted the value for sys_message.is_deleted
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_message
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SysMessage other = (SysMessage) that;
        return (this.getMessageId() == null ? other.getMessageId() == null : this.getMessageId().equals(other.getMessageId()))
            && (this.getContainer() == null ? other.getContainer() == null : this.getContainer().equals(other.getContainer()))
            && (this.getProducer() == null ? other.getProducer() == null : this.getProducer().equals(other.getProducer()))
            && (this.getConsumer() == null ? other.getConsumer() == null : this.getConsumer().equals(other.getConsumer()))
            && (this.getPriority() == null ? other.getPriority() == null : this.getPriority().equals(other.getPriority()))
            && (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
            && (this.getMessage() == null ? other.getMessage() == null : this.getMessage().equals(other.getMessage()))
            && (this.getTime() == null ? other.getTime() == null : this.getTime().equals(other.getTime()))
            && (this.getReadNum() == null ? other.getReadNum() == null : this.getReadNum().equals(other.getReadNum()))
            && (this.getLastReadTime() == null ? other.getLastReadTime() == null : this.getLastReadTime().equals(other.getLastReadTime()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getCreator() == null ? other.getCreator() == null : this.getCreator().equals(other.getCreator()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getAmender() == null ? other.getAmender() == null : this.getAmender().equals(other.getAmender()))
            && (this.getAmendTime() == null ? other.getAmendTime() == null : this.getAmendTime().equals(other.getAmendTime()))
            && (this.getAccessGroup() == null ? other.getAccessGroup() == null : this.getAccessGroup().equals(other.getAccessGroup()))
            && (this.getRecordVersion() == null ? other.getRecordVersion() == null : this.getRecordVersion().equals(other.getRecordVersion()))
            && (this.getIsDeleted() == null ? other.getIsDeleted() == null : this.getIsDeleted().equals(other.getIsDeleted()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_message
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getMessageId() == null) ? 0 : getMessageId().hashCode());
        result = prime * result + ((getContainer() == null) ? 0 : getContainer().hashCode());
        result = prime * result + ((getProducer() == null) ? 0 : getProducer().hashCode());
        result = prime * result + ((getConsumer() == null) ? 0 : getConsumer().hashCode());
        result = prime * result + ((getPriority() == null) ? 0 : getPriority().hashCode());
        result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
        result = prime * result + ((getMessage() == null) ? 0 : getMessage().hashCode());
        result = prime * result + ((getTime() == null) ? 0 : getTime().hashCode());
        result = prime * result + ((getReadNum() == null) ? 0 : getReadNum().hashCode());
        result = prime * result + ((getLastReadTime() == null) ? 0 : getLastReadTime().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getCreator() == null) ? 0 : getCreator().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getAmender() == null) ? 0 : getAmender().hashCode());
        result = prime * result + ((getAmendTime() == null) ? 0 : getAmendTime().hashCode());
        result = prime * result + ((getAccessGroup() == null) ? 0 : getAccessGroup().hashCode());
        result = prime * result + ((getRecordVersion() == null) ? 0 : getRecordVersion().hashCode());
        result = prime * result + ((getIsDeleted() == null) ? 0 : getIsDeleted().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_message
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", messageId=").append(messageId);
        sb.append(", container=").append(container);
        sb.append(", producer=").append(producer);
        sb.append(", consumer=").append(consumer);
        sb.append(", priority=").append(priority);
        sb.append(", title=").append(title);
        sb.append(", message=").append(message);
        sb.append(", time=").append(time);
        sb.append(", readNum=").append(readNum);
        sb.append(", lastReadTime=").append(lastReadTime);
        sb.append(", type=").append(type);
        sb.append(", creator=").append(creator);
        sb.append(", createTime=").append(createTime);
        sb.append(", amender=").append(amender);
        sb.append(", amendTime=").append(amendTime);
        sb.append(", accessGroup=").append(accessGroup);
        sb.append(", recordVersion=").append(recordVersion);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}