package com.stock.dao.model.sys;

import java.io.Serializable;
import java.util.Date;

public class SysOrganizationStructure implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization_structure.organization_structure_id
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private Integer organizationStructureId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization_structure.superior_id
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private Integer superiorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization_structure.code_common_set_id
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private Integer codeCommonSetId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization_structure.code_name
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private String codeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization_structure.type
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization_structure.name
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization_structure.office_native_name
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private String officeNativeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization_structure.abbrev
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private String abbrev;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization_structure.business_register_no
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private String businessRegisterNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization_structure.tax_register_no
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private String taxRegisterNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization_structure.port_code
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private String portCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization_structure.contact
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private String contact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization_structure.email
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization_structure.tel
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization_structure.supplier_type
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private String supplierType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization_structure.cust_type
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private String custType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization_structure.fax
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private String fax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization_structure.address
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization_structure.is_internal
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private Integer isInternal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization_structure.is_customer
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private Integer isCustomer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization_structure.is_supplier
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private Integer isSupplier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization_structure.active
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private Integer active;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization_structure.xchgr_name
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private String xchgrName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization_structure.company_code
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private String companyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization_structure.home_currency
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private String homeCurrency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization_structure.settle_office
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private String settleOffice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization_structure.bl_content
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private String blContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization_structure.company_id
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private Integer companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization_structure.cust_id
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private String custId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization_structure.cust_code
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private String custCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization_structure.function_type
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private String functionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization_structure.region_id
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private Integer regionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization_structure.region_code
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private String regionCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization_structure.port_id
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private Integer portId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization_structure.language
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private String language;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization_structure.superior_office_id
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private String superiorOfficeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization_structure.auto_internal
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private Integer autoInternal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization_structure.deleted
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private Integer deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization_structure.input_user
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private String inputUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization_structure.input_user_name
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private String inputUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization_structure.input_office
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private String inputOffice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization_structure.user_system
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private Integer userSystem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization_structure.contry_id
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private Integer contryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization_structure.country_code
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private String countryCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization_structure.city_id
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private Integer cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization_structure.city_code
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private String cityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization_structure.is_dept
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private Integer isDept;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization_structure.relaction_tag
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private String relactionTag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization_structure.booking_process_type
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private Integer bookingProcessType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization_structure.not_statistic_flag
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private Integer notStatisticFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization_structure.website_address
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private String websiteAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization_structure.description
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization_structure.creator
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private Integer creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization_structure.create_time
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization_structure.amender
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private Integer amender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization_structure.amend_time
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private Date amendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization_structure.access_group
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private Integer accessGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization_structure.record_version
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private Integer recordVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization_structure.is_deleted
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private Integer isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_organization_structure
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization_structure.organization_structure_id
     *
     * @return the value of sys_organization_structure.organization_structure_id
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public Integer getOrganizationStructureId() {
        return organizationStructureId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization_structure.organization_structure_id
     *
     * @param organizationStructureId the value for sys_organization_structure.organization_structure_id
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setOrganizationStructureId(Integer organizationStructureId) {
        this.organizationStructureId = organizationStructureId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization_structure.superior_id
     *
     * @return the value of sys_organization_structure.superior_id
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public Integer getSuperiorId() {
        return superiorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization_structure.superior_id
     *
     * @param superiorId the value for sys_organization_structure.superior_id
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setSuperiorId(Integer superiorId) {
        this.superiorId = superiorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization_structure.code_common_set_id
     *
     * @return the value of sys_organization_structure.code_common_set_id
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public Integer getCodeCommonSetId() {
        return codeCommonSetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization_structure.code_common_set_id
     *
     * @param codeCommonSetId the value for sys_organization_structure.code_common_set_id
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setCodeCommonSetId(Integer codeCommonSetId) {
        this.codeCommonSetId = codeCommonSetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization_structure.code_name
     *
     * @return the value of sys_organization_structure.code_name
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public String getCodeName() {
        return codeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization_structure.code_name
     *
     * @param codeName the value for sys_organization_structure.code_name
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setCodeName(String codeName) {
        this.codeName = codeName == null ? null : codeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization_structure.type
     *
     * @return the value of sys_organization_structure.type
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization_structure.type
     *
     * @param type the value for sys_organization_structure.type
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization_structure.name
     *
     * @return the value of sys_organization_structure.name
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization_structure.name
     *
     * @param name the value for sys_organization_structure.name
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization_structure.office_native_name
     *
     * @return the value of sys_organization_structure.office_native_name
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public String getOfficeNativeName() {
        return officeNativeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization_structure.office_native_name
     *
     * @param officeNativeName the value for sys_organization_structure.office_native_name
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setOfficeNativeName(String officeNativeName) {
        this.officeNativeName = officeNativeName == null ? null : officeNativeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization_structure.abbrev
     *
     * @return the value of sys_organization_structure.abbrev
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public String getAbbrev() {
        return abbrev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization_structure.abbrev
     *
     * @param abbrev the value for sys_organization_structure.abbrev
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setAbbrev(String abbrev) {
        this.abbrev = abbrev == null ? null : abbrev.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization_structure.business_register_no
     *
     * @return the value of sys_organization_structure.business_register_no
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public String getBusinessRegisterNo() {
        return businessRegisterNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization_structure.business_register_no
     *
     * @param businessRegisterNo the value for sys_organization_structure.business_register_no
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setBusinessRegisterNo(String businessRegisterNo) {
        this.businessRegisterNo = businessRegisterNo == null ? null : businessRegisterNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization_structure.tax_register_no
     *
     * @return the value of sys_organization_structure.tax_register_no
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public String getTaxRegisterNo() {
        return taxRegisterNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization_structure.tax_register_no
     *
     * @param taxRegisterNo the value for sys_organization_structure.tax_register_no
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setTaxRegisterNo(String taxRegisterNo) {
        this.taxRegisterNo = taxRegisterNo == null ? null : taxRegisterNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization_structure.port_code
     *
     * @return the value of sys_organization_structure.port_code
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public String getPortCode() {
        return portCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization_structure.port_code
     *
     * @param portCode the value for sys_organization_structure.port_code
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setPortCode(String portCode) {
        this.portCode = portCode == null ? null : portCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization_structure.contact
     *
     * @return the value of sys_organization_structure.contact
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization_structure.contact
     *
     * @param contact the value for sys_organization_structure.contact
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setContact(String contact) {
        this.contact = contact == null ? null : contact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization_structure.email
     *
     * @return the value of sys_organization_structure.email
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization_structure.email
     *
     * @param email the value for sys_organization_structure.email
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization_structure.tel
     *
     * @return the value of sys_organization_structure.tel
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization_structure.tel
     *
     * @param tel the value for sys_organization_structure.tel
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization_structure.supplier_type
     *
     * @return the value of sys_organization_structure.supplier_type
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public String getSupplierType() {
        return supplierType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization_structure.supplier_type
     *
     * @param supplierType the value for sys_organization_structure.supplier_type
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setSupplierType(String supplierType) {
        this.supplierType = supplierType == null ? null : supplierType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization_structure.cust_type
     *
     * @return the value of sys_organization_structure.cust_type
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public String getCustType() {
        return custType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization_structure.cust_type
     *
     * @param custType the value for sys_organization_structure.cust_type
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setCustType(String custType) {
        this.custType = custType == null ? null : custType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization_structure.fax
     *
     * @return the value of sys_organization_structure.fax
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization_structure.fax
     *
     * @param fax the value for sys_organization_structure.fax
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization_structure.address
     *
     * @return the value of sys_organization_structure.address
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization_structure.address
     *
     * @param address the value for sys_organization_structure.address
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization_structure.is_internal
     *
     * @return the value of sys_organization_structure.is_internal
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public Integer getIsInternal() {
        return isInternal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization_structure.is_internal
     *
     * @param isInternal the value for sys_organization_structure.is_internal
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setIsInternal(Integer isInternal) {
        this.isInternal = isInternal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization_structure.is_customer
     *
     * @return the value of sys_organization_structure.is_customer
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public Integer getIsCustomer() {
        return isCustomer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization_structure.is_customer
     *
     * @param isCustomer the value for sys_organization_structure.is_customer
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setIsCustomer(Integer isCustomer) {
        this.isCustomer = isCustomer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization_structure.is_supplier
     *
     * @return the value of sys_organization_structure.is_supplier
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public Integer getIsSupplier() {
        return isSupplier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization_structure.is_supplier
     *
     * @param isSupplier the value for sys_organization_structure.is_supplier
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setIsSupplier(Integer isSupplier) {
        this.isSupplier = isSupplier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization_structure.active
     *
     * @return the value of sys_organization_structure.active
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public Integer getActive() {
        return active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization_structure.active
     *
     * @param active the value for sys_organization_structure.active
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setActive(Integer active) {
        this.active = active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization_structure.xchgr_name
     *
     * @return the value of sys_organization_structure.xchgr_name
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public String getXchgrName() {
        return xchgrName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization_structure.xchgr_name
     *
     * @param xchgrName the value for sys_organization_structure.xchgr_name
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setXchgrName(String xchgrName) {
        this.xchgrName = xchgrName == null ? null : xchgrName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization_structure.company_code
     *
     * @return the value of sys_organization_structure.company_code
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public String getCompanyCode() {
        return companyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization_structure.company_code
     *
     * @param companyCode the value for sys_organization_structure.company_code
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setCompanyCode(String companyCode) {
        this.companyCode = companyCode == null ? null : companyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization_structure.home_currency
     *
     * @return the value of sys_organization_structure.home_currency
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public String getHomeCurrency() {
        return homeCurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization_structure.home_currency
     *
     * @param homeCurrency the value for sys_organization_structure.home_currency
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setHomeCurrency(String homeCurrency) {
        this.homeCurrency = homeCurrency == null ? null : homeCurrency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization_structure.settle_office
     *
     * @return the value of sys_organization_structure.settle_office
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public String getSettleOffice() {
        return settleOffice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization_structure.settle_office
     *
     * @param settleOffice the value for sys_organization_structure.settle_office
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setSettleOffice(String settleOffice) {
        this.settleOffice = settleOffice == null ? null : settleOffice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization_structure.bl_content
     *
     * @return the value of sys_organization_structure.bl_content
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public String getBlContent() {
        return blContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization_structure.bl_content
     *
     * @param blContent the value for sys_organization_structure.bl_content
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setBlContent(String blContent) {
        this.blContent = blContent == null ? null : blContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization_structure.company_id
     *
     * @return the value of sys_organization_structure.company_id
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization_structure.company_id
     *
     * @param companyId the value for sys_organization_structure.company_id
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization_structure.cust_id
     *
     * @return the value of sys_organization_structure.cust_id
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public String getCustId() {
        return custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization_structure.cust_id
     *
     * @param custId the value for sys_organization_structure.cust_id
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setCustId(String custId) {
        this.custId = custId == null ? null : custId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization_structure.cust_code
     *
     * @return the value of sys_organization_structure.cust_code
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public String getCustCode() {
        return custCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization_structure.cust_code
     *
     * @param custCode the value for sys_organization_structure.cust_code
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setCustCode(String custCode) {
        this.custCode = custCode == null ? null : custCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization_structure.function_type
     *
     * @return the value of sys_organization_structure.function_type
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public String getFunctionType() {
        return functionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization_structure.function_type
     *
     * @param functionType the value for sys_organization_structure.function_type
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setFunctionType(String functionType) {
        this.functionType = functionType == null ? null : functionType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization_structure.region_id
     *
     * @return the value of sys_organization_structure.region_id
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public Integer getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization_structure.region_id
     *
     * @param regionId the value for sys_organization_structure.region_id
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setRegionId(Integer regionId) {
        this.regionId = regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization_structure.region_code
     *
     * @return the value of sys_organization_structure.region_code
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public String getRegionCode() {
        return regionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization_structure.region_code
     *
     * @param regionCode the value for sys_organization_structure.region_code
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setRegionCode(String regionCode) {
        this.regionCode = regionCode == null ? null : regionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization_structure.port_id
     *
     * @return the value of sys_organization_structure.port_id
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public Integer getPortId() {
        return portId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization_structure.port_id
     *
     * @param portId the value for sys_organization_structure.port_id
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setPortId(Integer portId) {
        this.portId = portId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization_structure.language
     *
     * @return the value of sys_organization_structure.language
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public String getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization_structure.language
     *
     * @param language the value for sys_organization_structure.language
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setLanguage(String language) {
        this.language = language == null ? null : language.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization_structure.superior_office_id
     *
     * @return the value of sys_organization_structure.superior_office_id
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public String getSuperiorOfficeId() {
        return superiorOfficeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization_structure.superior_office_id
     *
     * @param superiorOfficeId the value for sys_organization_structure.superior_office_id
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setSuperiorOfficeId(String superiorOfficeId) {
        this.superiorOfficeId = superiorOfficeId == null ? null : superiorOfficeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization_structure.auto_internal
     *
     * @return the value of sys_organization_structure.auto_internal
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public Integer getAutoInternal() {
        return autoInternal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization_structure.auto_internal
     *
     * @param autoInternal the value for sys_organization_structure.auto_internal
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setAutoInternal(Integer autoInternal) {
        this.autoInternal = autoInternal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization_structure.deleted
     *
     * @return the value of sys_organization_structure.deleted
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization_structure.deleted
     *
     * @param deleted the value for sys_organization_structure.deleted
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization_structure.input_user
     *
     * @return the value of sys_organization_structure.input_user
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public String getInputUser() {
        return inputUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization_structure.input_user
     *
     * @param inputUser the value for sys_organization_structure.input_user
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setInputUser(String inputUser) {
        this.inputUser = inputUser == null ? null : inputUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization_structure.input_user_name
     *
     * @return the value of sys_organization_structure.input_user_name
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public String getInputUserName() {
        return inputUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization_structure.input_user_name
     *
     * @param inputUserName the value for sys_organization_structure.input_user_name
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setInputUserName(String inputUserName) {
        this.inputUserName = inputUserName == null ? null : inputUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization_structure.input_office
     *
     * @return the value of sys_organization_structure.input_office
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public String getInputOffice() {
        return inputOffice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization_structure.input_office
     *
     * @param inputOffice the value for sys_organization_structure.input_office
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setInputOffice(String inputOffice) {
        this.inputOffice = inputOffice == null ? null : inputOffice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization_structure.user_system
     *
     * @return the value of sys_organization_structure.user_system
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public Integer getUserSystem() {
        return userSystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization_structure.user_system
     *
     * @param userSystem the value for sys_organization_structure.user_system
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setUserSystem(Integer userSystem) {
        this.userSystem = userSystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization_structure.contry_id
     *
     * @return the value of sys_organization_structure.contry_id
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public Integer getContryId() {
        return contryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization_structure.contry_id
     *
     * @param contryId the value for sys_organization_structure.contry_id
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setContryId(Integer contryId) {
        this.contryId = contryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization_structure.country_code
     *
     * @return the value of sys_organization_structure.country_code
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public String getCountryCode() {
        return countryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization_structure.country_code
     *
     * @param countryCode the value for sys_organization_structure.country_code
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode == null ? null : countryCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization_structure.city_id
     *
     * @return the value of sys_organization_structure.city_id
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization_structure.city_id
     *
     * @param cityId the value for sys_organization_structure.city_id
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization_structure.city_code
     *
     * @return the value of sys_organization_structure.city_code
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization_structure.city_code
     *
     * @param cityCode the value for sys_organization_structure.city_code
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode == null ? null : cityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization_structure.is_dept
     *
     * @return the value of sys_organization_structure.is_dept
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public Integer getIsDept() {
        return isDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization_structure.is_dept
     *
     * @param isDept the value for sys_organization_structure.is_dept
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setIsDept(Integer isDept) {
        this.isDept = isDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization_structure.relaction_tag
     *
     * @return the value of sys_organization_structure.relaction_tag
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public String getRelactionTag() {
        return relactionTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization_structure.relaction_tag
     *
     * @param relactionTag the value for sys_organization_structure.relaction_tag
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setRelactionTag(String relactionTag) {
        this.relactionTag = relactionTag == null ? null : relactionTag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization_structure.booking_process_type
     *
     * @return the value of sys_organization_structure.booking_process_type
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public Integer getBookingProcessType() {
        return bookingProcessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization_structure.booking_process_type
     *
     * @param bookingProcessType the value for sys_organization_structure.booking_process_type
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setBookingProcessType(Integer bookingProcessType) {
        this.bookingProcessType = bookingProcessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization_structure.not_statistic_flag
     *
     * @return the value of sys_organization_structure.not_statistic_flag
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public Integer getNotStatisticFlag() {
        return notStatisticFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization_structure.not_statistic_flag
     *
     * @param notStatisticFlag the value for sys_organization_structure.not_statistic_flag
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setNotStatisticFlag(Integer notStatisticFlag) {
        this.notStatisticFlag = notStatisticFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization_structure.website_address
     *
     * @return the value of sys_organization_structure.website_address
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public String getWebsiteAddress() {
        return websiteAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization_structure.website_address
     *
     * @param websiteAddress the value for sys_organization_structure.website_address
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setWebsiteAddress(String websiteAddress) {
        this.websiteAddress = websiteAddress == null ? null : websiteAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization_structure.description
     *
     * @return the value of sys_organization_structure.description
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization_structure.description
     *
     * @param description the value for sys_organization_structure.description
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization_structure.creator
     *
     * @return the value of sys_organization_structure.creator
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization_structure.creator
     *
     * @param creator the value for sys_organization_structure.creator
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization_structure.create_time
     *
     * @return the value of sys_organization_structure.create_time
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization_structure.create_time
     *
     * @param createTime the value for sys_organization_structure.create_time
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization_structure.amender
     *
     * @return the value of sys_organization_structure.amender
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public Integer getAmender() {
        return amender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization_structure.amender
     *
     * @param amender the value for sys_organization_structure.amender
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setAmender(Integer amender) {
        this.amender = amender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization_structure.amend_time
     *
     * @return the value of sys_organization_structure.amend_time
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public Date getAmendTime() {
        return amendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization_structure.amend_time
     *
     * @param amendTime the value for sys_organization_structure.amend_time
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setAmendTime(Date amendTime) {
        this.amendTime = amendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization_structure.access_group
     *
     * @return the value of sys_organization_structure.access_group
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public Integer getAccessGroup() {
        return accessGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization_structure.access_group
     *
     * @param accessGroup the value for sys_organization_structure.access_group
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setAccessGroup(Integer accessGroup) {
        this.accessGroup = accessGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization_structure.record_version
     *
     * @return the value of sys_organization_structure.record_version
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public Integer getRecordVersion() {
        return recordVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization_structure.record_version
     *
     * @param recordVersion the value for sys_organization_structure.record_version
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setRecordVersion(Integer recordVersion) {
        this.recordVersion = recordVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization_structure.is_deleted
     *
     * @return the value of sys_organization_structure.is_deleted
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization_structure.is_deleted
     *
     * @param isDeleted the value for sys_organization_structure.is_deleted
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization_structure
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SysOrganizationStructure other = (SysOrganizationStructure) that;
        return (this.getOrganizationStructureId() == null ? other.getOrganizationStructureId() == null : this.getOrganizationStructureId().equals(other.getOrganizationStructureId()))
            && (this.getSuperiorId() == null ? other.getSuperiorId() == null : this.getSuperiorId().equals(other.getSuperiorId()))
            && (this.getCodeCommonSetId() == null ? other.getCodeCommonSetId() == null : this.getCodeCommonSetId().equals(other.getCodeCommonSetId()))
            && (this.getCodeName() == null ? other.getCodeName() == null : this.getCodeName().equals(other.getCodeName()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getOfficeNativeName() == null ? other.getOfficeNativeName() == null : this.getOfficeNativeName().equals(other.getOfficeNativeName()))
            && (this.getAbbrev() == null ? other.getAbbrev() == null : this.getAbbrev().equals(other.getAbbrev()))
            && (this.getBusinessRegisterNo() == null ? other.getBusinessRegisterNo() == null : this.getBusinessRegisterNo().equals(other.getBusinessRegisterNo()))
            && (this.getTaxRegisterNo() == null ? other.getTaxRegisterNo() == null : this.getTaxRegisterNo().equals(other.getTaxRegisterNo()))
            && (this.getPortCode() == null ? other.getPortCode() == null : this.getPortCode().equals(other.getPortCode()))
            && (this.getContact() == null ? other.getContact() == null : this.getContact().equals(other.getContact()))
            && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
            && (this.getTel() == null ? other.getTel() == null : this.getTel().equals(other.getTel()))
            && (this.getSupplierType() == null ? other.getSupplierType() == null : this.getSupplierType().equals(other.getSupplierType()))
            && (this.getCustType() == null ? other.getCustType() == null : this.getCustType().equals(other.getCustType()))
            && (this.getFax() == null ? other.getFax() == null : this.getFax().equals(other.getFax()))
            && (this.getAddress() == null ? other.getAddress() == null : this.getAddress().equals(other.getAddress()))
            && (this.getIsInternal() == null ? other.getIsInternal() == null : this.getIsInternal().equals(other.getIsInternal()))
            && (this.getIsCustomer() == null ? other.getIsCustomer() == null : this.getIsCustomer().equals(other.getIsCustomer()))
            && (this.getIsSupplier() == null ? other.getIsSupplier() == null : this.getIsSupplier().equals(other.getIsSupplier()))
            && (this.getActive() == null ? other.getActive() == null : this.getActive().equals(other.getActive()))
            && (this.getXchgrName() == null ? other.getXchgrName() == null : this.getXchgrName().equals(other.getXchgrName()))
            && (this.getCompanyCode() == null ? other.getCompanyCode() == null : this.getCompanyCode().equals(other.getCompanyCode()))
            && (this.getHomeCurrency() == null ? other.getHomeCurrency() == null : this.getHomeCurrency().equals(other.getHomeCurrency()))
            && (this.getSettleOffice() == null ? other.getSettleOffice() == null : this.getSettleOffice().equals(other.getSettleOffice()))
            && (this.getBlContent() == null ? other.getBlContent() == null : this.getBlContent().equals(other.getBlContent()))
            && (this.getCompanyId() == null ? other.getCompanyId() == null : this.getCompanyId().equals(other.getCompanyId()))
            && (this.getCustId() == null ? other.getCustId() == null : this.getCustId().equals(other.getCustId()))
            && (this.getCustCode() == null ? other.getCustCode() == null : this.getCustCode().equals(other.getCustCode()))
            && (this.getFunctionType() == null ? other.getFunctionType() == null : this.getFunctionType().equals(other.getFunctionType()))
            && (this.getRegionId() == null ? other.getRegionId() == null : this.getRegionId().equals(other.getRegionId()))
            && (this.getRegionCode() == null ? other.getRegionCode() == null : this.getRegionCode().equals(other.getRegionCode()))
            && (this.getPortId() == null ? other.getPortId() == null : this.getPortId().equals(other.getPortId()))
            && (this.getLanguage() == null ? other.getLanguage() == null : this.getLanguage().equals(other.getLanguage()))
            && (this.getSuperiorOfficeId() == null ? other.getSuperiorOfficeId() == null : this.getSuperiorOfficeId().equals(other.getSuperiorOfficeId()))
            && (this.getAutoInternal() == null ? other.getAutoInternal() == null : this.getAutoInternal().equals(other.getAutoInternal()))
            && (this.getDeleted() == null ? other.getDeleted() == null : this.getDeleted().equals(other.getDeleted()))
            && (this.getInputUser() == null ? other.getInputUser() == null : this.getInputUser().equals(other.getInputUser()))
            && (this.getInputUserName() == null ? other.getInputUserName() == null : this.getInputUserName().equals(other.getInputUserName()))
            && (this.getInputOffice() == null ? other.getInputOffice() == null : this.getInputOffice().equals(other.getInputOffice()))
            && (this.getUserSystem() == null ? other.getUserSystem() == null : this.getUserSystem().equals(other.getUserSystem()))
            && (this.getContryId() == null ? other.getContryId() == null : this.getContryId().equals(other.getContryId()))
            && (this.getCountryCode() == null ? other.getCountryCode() == null : this.getCountryCode().equals(other.getCountryCode()))
            && (this.getCityId() == null ? other.getCityId() == null : this.getCityId().equals(other.getCityId()))
            && (this.getCityCode() == null ? other.getCityCode() == null : this.getCityCode().equals(other.getCityCode()))
            && (this.getIsDept() == null ? other.getIsDept() == null : this.getIsDept().equals(other.getIsDept()))
            && (this.getRelactionTag() == null ? other.getRelactionTag() == null : this.getRelactionTag().equals(other.getRelactionTag()))
            && (this.getBookingProcessType() == null ? other.getBookingProcessType() == null : this.getBookingProcessType().equals(other.getBookingProcessType()))
            && (this.getNotStatisticFlag() == null ? other.getNotStatisticFlag() == null : this.getNotStatisticFlag().equals(other.getNotStatisticFlag()))
            && (this.getWebsiteAddress() == null ? other.getWebsiteAddress() == null : this.getWebsiteAddress().equals(other.getWebsiteAddress()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getCreator() == null ? other.getCreator() == null : this.getCreator().equals(other.getCreator()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getAmender() == null ? other.getAmender() == null : this.getAmender().equals(other.getAmender()))
            && (this.getAmendTime() == null ? other.getAmendTime() == null : this.getAmendTime().equals(other.getAmendTime()))
            && (this.getAccessGroup() == null ? other.getAccessGroup() == null : this.getAccessGroup().equals(other.getAccessGroup()))
            && (this.getRecordVersion() == null ? other.getRecordVersion() == null : this.getRecordVersion().equals(other.getRecordVersion()))
            && (this.getIsDeleted() == null ? other.getIsDeleted() == null : this.getIsDeleted().equals(other.getIsDeleted()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization_structure
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getOrganizationStructureId() == null) ? 0 : getOrganizationStructureId().hashCode());
        result = prime * result + ((getSuperiorId() == null) ? 0 : getSuperiorId().hashCode());
        result = prime * result + ((getCodeCommonSetId() == null) ? 0 : getCodeCommonSetId().hashCode());
        result = prime * result + ((getCodeName() == null) ? 0 : getCodeName().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getOfficeNativeName() == null) ? 0 : getOfficeNativeName().hashCode());
        result = prime * result + ((getAbbrev() == null) ? 0 : getAbbrev().hashCode());
        result = prime * result + ((getBusinessRegisterNo() == null) ? 0 : getBusinessRegisterNo().hashCode());
        result = prime * result + ((getTaxRegisterNo() == null) ? 0 : getTaxRegisterNo().hashCode());
        result = prime * result + ((getPortCode() == null) ? 0 : getPortCode().hashCode());
        result = prime * result + ((getContact() == null) ? 0 : getContact().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        result = prime * result + ((getTel() == null) ? 0 : getTel().hashCode());
        result = prime * result + ((getSupplierType() == null) ? 0 : getSupplierType().hashCode());
        result = prime * result + ((getCustType() == null) ? 0 : getCustType().hashCode());
        result = prime * result + ((getFax() == null) ? 0 : getFax().hashCode());
        result = prime * result + ((getAddress() == null) ? 0 : getAddress().hashCode());
        result = prime * result + ((getIsInternal() == null) ? 0 : getIsInternal().hashCode());
        result = prime * result + ((getIsCustomer() == null) ? 0 : getIsCustomer().hashCode());
        result = prime * result + ((getIsSupplier() == null) ? 0 : getIsSupplier().hashCode());
        result = prime * result + ((getActive() == null) ? 0 : getActive().hashCode());
        result = prime * result + ((getXchgrName() == null) ? 0 : getXchgrName().hashCode());
        result = prime * result + ((getCompanyCode() == null) ? 0 : getCompanyCode().hashCode());
        result = prime * result + ((getHomeCurrency() == null) ? 0 : getHomeCurrency().hashCode());
        result = prime * result + ((getSettleOffice() == null) ? 0 : getSettleOffice().hashCode());
        result = prime * result + ((getBlContent() == null) ? 0 : getBlContent().hashCode());
        result = prime * result + ((getCompanyId() == null) ? 0 : getCompanyId().hashCode());
        result = prime * result + ((getCustId() == null) ? 0 : getCustId().hashCode());
        result = prime * result + ((getCustCode() == null) ? 0 : getCustCode().hashCode());
        result = prime * result + ((getFunctionType() == null) ? 0 : getFunctionType().hashCode());
        result = prime * result + ((getRegionId() == null) ? 0 : getRegionId().hashCode());
        result = prime * result + ((getRegionCode() == null) ? 0 : getRegionCode().hashCode());
        result = prime * result + ((getPortId() == null) ? 0 : getPortId().hashCode());
        result = prime * result + ((getLanguage() == null) ? 0 : getLanguage().hashCode());
        result = prime * result + ((getSuperiorOfficeId() == null) ? 0 : getSuperiorOfficeId().hashCode());
        result = prime * result + ((getAutoInternal() == null) ? 0 : getAutoInternal().hashCode());
        result = prime * result + ((getDeleted() == null) ? 0 : getDeleted().hashCode());
        result = prime * result + ((getInputUser() == null) ? 0 : getInputUser().hashCode());
        result = prime * result + ((getInputUserName() == null) ? 0 : getInputUserName().hashCode());
        result = prime * result + ((getInputOffice() == null) ? 0 : getInputOffice().hashCode());
        result = prime * result + ((getUserSystem() == null) ? 0 : getUserSystem().hashCode());
        result = prime * result + ((getContryId() == null) ? 0 : getContryId().hashCode());
        result = prime * result + ((getCountryCode() == null) ? 0 : getCountryCode().hashCode());
        result = prime * result + ((getCityId() == null) ? 0 : getCityId().hashCode());
        result = prime * result + ((getCityCode() == null) ? 0 : getCityCode().hashCode());
        result = prime * result + ((getIsDept() == null) ? 0 : getIsDept().hashCode());
        result = prime * result + ((getRelactionTag() == null) ? 0 : getRelactionTag().hashCode());
        result = prime * result + ((getBookingProcessType() == null) ? 0 : getBookingProcessType().hashCode());
        result = prime * result + ((getNotStatisticFlag() == null) ? 0 : getNotStatisticFlag().hashCode());
        result = prime * result + ((getWebsiteAddress() == null) ? 0 : getWebsiteAddress().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getCreator() == null) ? 0 : getCreator().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getAmender() == null) ? 0 : getAmender().hashCode());
        result = prime * result + ((getAmendTime() == null) ? 0 : getAmendTime().hashCode());
        result = prime * result + ((getAccessGroup() == null) ? 0 : getAccessGroup().hashCode());
        result = prime * result + ((getRecordVersion() == null) ? 0 : getRecordVersion().hashCode());
        result = prime * result + ((getIsDeleted() == null) ? 0 : getIsDeleted().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization_structure
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", organizationStructureId=").append(organizationStructureId);
        sb.append(", superiorId=").append(superiorId);
        sb.append(", codeCommonSetId=").append(codeCommonSetId);
        sb.append(", codeName=").append(codeName);
        sb.append(", type=").append(type);
        sb.append(", name=").append(name);
        sb.append(", officeNativeName=").append(officeNativeName);
        sb.append(", abbrev=").append(abbrev);
        sb.append(", businessRegisterNo=").append(businessRegisterNo);
        sb.append(", taxRegisterNo=").append(taxRegisterNo);
        sb.append(", portCode=").append(portCode);
        sb.append(", contact=").append(contact);
        sb.append(", email=").append(email);
        sb.append(", tel=").append(tel);
        sb.append(", supplierType=").append(supplierType);
        sb.append(", custType=").append(custType);
        sb.append(", fax=").append(fax);
        sb.append(", address=").append(address);
        sb.append(", isInternal=").append(isInternal);
        sb.append(", isCustomer=").append(isCustomer);
        sb.append(", isSupplier=").append(isSupplier);
        sb.append(", active=").append(active);
        sb.append(", xchgrName=").append(xchgrName);
        sb.append(", companyCode=").append(companyCode);
        sb.append(", homeCurrency=").append(homeCurrency);
        sb.append(", settleOffice=").append(settleOffice);
        sb.append(", blContent=").append(blContent);
        sb.append(", companyId=").append(companyId);
        sb.append(", custId=").append(custId);
        sb.append(", custCode=").append(custCode);
        sb.append(", functionType=").append(functionType);
        sb.append(", regionId=").append(regionId);
        sb.append(", regionCode=").append(regionCode);
        sb.append(", portId=").append(portId);
        sb.append(", language=").append(language);
        sb.append(", superiorOfficeId=").append(superiorOfficeId);
        sb.append(", autoInternal=").append(autoInternal);
        sb.append(", deleted=").append(deleted);
        sb.append(", inputUser=").append(inputUser);
        sb.append(", inputUserName=").append(inputUserName);
        sb.append(", inputOffice=").append(inputOffice);
        sb.append(", userSystem=").append(userSystem);
        sb.append(", contryId=").append(contryId);
        sb.append(", countryCode=").append(countryCode);
        sb.append(", cityId=").append(cityId);
        sb.append(", cityCode=").append(cityCode);
        sb.append(", isDept=").append(isDept);
        sb.append(", relactionTag=").append(relactionTag);
        sb.append(", bookingProcessType=").append(bookingProcessType);
        sb.append(", notStatisticFlag=").append(notStatisticFlag);
        sb.append(", websiteAddress=").append(websiteAddress);
        sb.append(", description=").append(description);
        sb.append(", creator=").append(creator);
        sb.append(", createTime=").append(createTime);
        sb.append(", amender=").append(amender);
        sb.append(", amendTime=").append(amendTime);
        sb.append(", accessGroup=").append(accessGroup);
        sb.append(", recordVersion=").append(recordVersion);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}