package com.stock.dao.model.sys;

import com.stock.dao.page.Page;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SysUserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_user
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_user
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_user
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_user
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    protected Page page;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public SysUserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public void setPage(Page page) {
        this.page=page;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public Page getPage() {
        return page;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_user
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNull() {
            addCriterion("username is null");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNotNull() {
            addCriterion("username is not null");
            return (Criteria) this;
        }

        public Criteria andUsernameEqualTo(String value) {
            addCriterion("username =", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotEqualTo(String value) {
            addCriterion("username <>", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThan(String value) {
            addCriterion("username >", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("username >=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThan(String value) {
            addCriterion("username <", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThanOrEqualTo(String value) {
            addCriterion("username <=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLike(String value) {
            addCriterion("username like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotLike(String value) {
            addCriterion("username not like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameIn(List<String> values) {
            addCriterion("username in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotIn(List<String> values) {
            addCriterion("username not in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameBetween(String value1, String value2) {
            addCriterion("username between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotBetween(String value1, String value2) {
            addCriterion("username not between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("password is null");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("password is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("password =", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("password <>", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("password >", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("password >=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("password <", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("password <=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("password like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("password not like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordIn(List<String> values) {
            addCriterion("password in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotIn(List<String> values) {
            addCriterion("password not in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("password between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("password not between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andSignatureIsNull() {
            addCriterion("signature is null");
            return (Criteria) this;
        }

        public Criteria andSignatureIsNotNull() {
            addCriterion("signature is not null");
            return (Criteria) this;
        }

        public Criteria andSignatureEqualTo(String value) {
            addCriterion("signature =", value, "signature");
            return (Criteria) this;
        }

        public Criteria andSignatureNotEqualTo(String value) {
            addCriterion("signature <>", value, "signature");
            return (Criteria) this;
        }

        public Criteria andSignatureGreaterThan(String value) {
            addCriterion("signature >", value, "signature");
            return (Criteria) this;
        }

        public Criteria andSignatureGreaterThanOrEqualTo(String value) {
            addCriterion("signature >=", value, "signature");
            return (Criteria) this;
        }

        public Criteria andSignatureLessThan(String value) {
            addCriterion("signature <", value, "signature");
            return (Criteria) this;
        }

        public Criteria andSignatureLessThanOrEqualTo(String value) {
            addCriterion("signature <=", value, "signature");
            return (Criteria) this;
        }

        public Criteria andSignatureLike(String value) {
            addCriterion("signature like", value, "signature");
            return (Criteria) this;
        }

        public Criteria andSignatureNotLike(String value) {
            addCriterion("signature not like", value, "signature");
            return (Criteria) this;
        }

        public Criteria andSignatureIn(List<String> values) {
            addCriterion("signature in", values, "signature");
            return (Criteria) this;
        }

        public Criteria andSignatureNotIn(List<String> values) {
            addCriterion("signature not in", values, "signature");
            return (Criteria) this;
        }

        public Criteria andSignatureBetween(String value1, String value2) {
            addCriterion("signature between", value1, value2, "signature");
            return (Criteria) this;
        }

        public Criteria andSignatureNotBetween(String value1, String value2) {
            addCriterion("signature not between", value1, value2, "signature");
            return (Criteria) this;
        }

        public Criteria andPwdModifyDateIsNull() {
            addCriterion("pwd_modify_date is null");
            return (Criteria) this;
        }

        public Criteria andPwdModifyDateIsNotNull() {
            addCriterion("pwd_modify_date is not null");
            return (Criteria) this;
        }

        public Criteria andPwdModifyDateEqualTo(Date value) {
            addCriterion("pwd_modify_date =", value, "pwdModifyDate");
            return (Criteria) this;
        }

        public Criteria andPwdModifyDateNotEqualTo(Date value) {
            addCriterion("pwd_modify_date <>", value, "pwdModifyDate");
            return (Criteria) this;
        }

        public Criteria andPwdModifyDateGreaterThan(Date value) {
            addCriterion("pwd_modify_date >", value, "pwdModifyDate");
            return (Criteria) this;
        }

        public Criteria andPwdModifyDateGreaterThanOrEqualTo(Date value) {
            addCriterion("pwd_modify_date >=", value, "pwdModifyDate");
            return (Criteria) this;
        }

        public Criteria andPwdModifyDateLessThan(Date value) {
            addCriterion("pwd_modify_date <", value, "pwdModifyDate");
            return (Criteria) this;
        }

        public Criteria andPwdModifyDateLessThanOrEqualTo(Date value) {
            addCriterion("pwd_modify_date <=", value, "pwdModifyDate");
            return (Criteria) this;
        }

        public Criteria andPwdModifyDateIn(List<Date> values) {
            addCriterion("pwd_modify_date in", values, "pwdModifyDate");
            return (Criteria) this;
        }

        public Criteria andPwdModifyDateNotIn(List<Date> values) {
            addCriterion("pwd_modify_date not in", values, "pwdModifyDate");
            return (Criteria) this;
        }

        public Criteria andPwdModifyDateBetween(Date value1, Date value2) {
            addCriterion("pwd_modify_date between", value1, value2, "pwdModifyDate");
            return (Criteria) this;
        }

        public Criteria andPwdModifyDateNotBetween(Date value1, Date value2) {
            addCriterion("pwd_modify_date not between", value1, value2, "pwdModifyDate");
            return (Criteria) this;
        }

        public Criteria andPwdEffectiveDayIsNull() {
            addCriterion("pwd_effective_day is null");
            return (Criteria) this;
        }

        public Criteria andPwdEffectiveDayIsNotNull() {
            addCriterion("pwd_effective_day is not null");
            return (Criteria) this;
        }

        public Criteria andPwdEffectiveDayEqualTo(Integer value) {
            addCriterion("pwd_effective_day =", value, "pwdEffectiveDay");
            return (Criteria) this;
        }

        public Criteria andPwdEffectiveDayNotEqualTo(Integer value) {
            addCriterion("pwd_effective_day <>", value, "pwdEffectiveDay");
            return (Criteria) this;
        }

        public Criteria andPwdEffectiveDayGreaterThan(Integer value) {
            addCriterion("pwd_effective_day >", value, "pwdEffectiveDay");
            return (Criteria) this;
        }

        public Criteria andPwdEffectiveDayGreaterThanOrEqualTo(Integer value) {
            addCriterion("pwd_effective_day >=", value, "pwdEffectiveDay");
            return (Criteria) this;
        }

        public Criteria andPwdEffectiveDayLessThan(Integer value) {
            addCriterion("pwd_effective_day <", value, "pwdEffectiveDay");
            return (Criteria) this;
        }

        public Criteria andPwdEffectiveDayLessThanOrEqualTo(Integer value) {
            addCriterion("pwd_effective_day <=", value, "pwdEffectiveDay");
            return (Criteria) this;
        }

        public Criteria andPwdEffectiveDayIn(List<Integer> values) {
            addCriterion("pwd_effective_day in", values, "pwdEffectiveDay");
            return (Criteria) this;
        }

        public Criteria andPwdEffectiveDayNotIn(List<Integer> values) {
            addCriterion("pwd_effective_day not in", values, "pwdEffectiveDay");
            return (Criteria) this;
        }

        public Criteria andPwdEffectiveDayBetween(Integer value1, Integer value2) {
            addCriterion("pwd_effective_day between", value1, value2, "pwdEffectiveDay");
            return (Criteria) this;
        }

        public Criteria andPwdEffectiveDayNotBetween(Integer value1, Integer value2) {
            addCriterion("pwd_effective_day not between", value1, value2, "pwdEffectiveDay");
            return (Criteria) this;
        }

        public Criteria andDefaultLangIsNull() {
            addCriterion("default_lang is null");
            return (Criteria) this;
        }

        public Criteria andDefaultLangIsNotNull() {
            addCriterion("default_lang is not null");
            return (Criteria) this;
        }

        public Criteria andDefaultLangEqualTo(String value) {
            addCriterion("default_lang =", value, "defaultLang");
            return (Criteria) this;
        }

        public Criteria andDefaultLangNotEqualTo(String value) {
            addCriterion("default_lang <>", value, "defaultLang");
            return (Criteria) this;
        }

        public Criteria andDefaultLangGreaterThan(String value) {
            addCriterion("default_lang >", value, "defaultLang");
            return (Criteria) this;
        }

        public Criteria andDefaultLangGreaterThanOrEqualTo(String value) {
            addCriterion("default_lang >=", value, "defaultLang");
            return (Criteria) this;
        }

        public Criteria andDefaultLangLessThan(String value) {
            addCriterion("default_lang <", value, "defaultLang");
            return (Criteria) this;
        }

        public Criteria andDefaultLangLessThanOrEqualTo(String value) {
            addCriterion("default_lang <=", value, "defaultLang");
            return (Criteria) this;
        }

        public Criteria andDefaultLangLike(String value) {
            addCriterion("default_lang like", value, "defaultLang");
            return (Criteria) this;
        }

        public Criteria andDefaultLangNotLike(String value) {
            addCriterion("default_lang not like", value, "defaultLang");
            return (Criteria) this;
        }

        public Criteria andDefaultLangIn(List<String> values) {
            addCriterion("default_lang in", values, "defaultLang");
            return (Criteria) this;
        }

        public Criteria andDefaultLangNotIn(List<String> values) {
            addCriterion("default_lang not in", values, "defaultLang");
            return (Criteria) this;
        }

        public Criteria andDefaultLangBetween(String value1, String value2) {
            addCriterion("default_lang between", value1, value2, "defaultLang");
            return (Criteria) this;
        }

        public Criteria andDefaultLangNotBetween(String value1, String value2) {
            addCriterion("default_lang not between", value1, value2, "defaultLang");
            return (Criteria) this;
        }

        public Criteria andCanLoginIsNull() {
            addCriterion("can_login is null");
            return (Criteria) this;
        }

        public Criteria andCanLoginIsNotNull() {
            addCriterion("can_login is not null");
            return (Criteria) this;
        }

        public Criteria andCanLoginEqualTo(Short value) {
            addCriterion("can_login =", value, "canLogin");
            return (Criteria) this;
        }

        public Criteria andCanLoginNotEqualTo(Short value) {
            addCriterion("can_login <>", value, "canLogin");
            return (Criteria) this;
        }

        public Criteria andCanLoginGreaterThan(Short value) {
            addCriterion("can_login >", value, "canLogin");
            return (Criteria) this;
        }

        public Criteria andCanLoginGreaterThanOrEqualTo(Short value) {
            addCriterion("can_login >=", value, "canLogin");
            return (Criteria) this;
        }

        public Criteria andCanLoginLessThan(Short value) {
            addCriterion("can_login <", value, "canLogin");
            return (Criteria) this;
        }

        public Criteria andCanLoginLessThanOrEqualTo(Short value) {
            addCriterion("can_login <=", value, "canLogin");
            return (Criteria) this;
        }

        public Criteria andCanLoginIn(List<Short> values) {
            addCriterion("can_login in", values, "canLogin");
            return (Criteria) this;
        }

        public Criteria andCanLoginNotIn(List<Short> values) {
            addCriterion("can_login not in", values, "canLogin");
            return (Criteria) this;
        }

        public Criteria andCanLoginBetween(Short value1, Short value2) {
            addCriterion("can_login between", value1, value2, "canLogin");
            return (Criteria) this;
        }

        public Criteria andCanLoginNotBetween(Short value1, Short value2) {
            addCriterion("can_login not between", value1, value2, "canLogin");
            return (Criteria) this;
        }

        public Criteria andCanLoginwebIsNull() {
            addCriterion("can_loginweb is null");
            return (Criteria) this;
        }

        public Criteria andCanLoginwebIsNotNull() {
            addCriterion("can_loginweb is not null");
            return (Criteria) this;
        }

        public Criteria andCanLoginwebEqualTo(Integer value) {
            addCriterion("can_loginweb =", value, "canLoginweb");
            return (Criteria) this;
        }

        public Criteria andCanLoginwebNotEqualTo(Integer value) {
            addCriterion("can_loginweb <>", value, "canLoginweb");
            return (Criteria) this;
        }

        public Criteria andCanLoginwebGreaterThan(Integer value) {
            addCriterion("can_loginweb >", value, "canLoginweb");
            return (Criteria) this;
        }

        public Criteria andCanLoginwebGreaterThanOrEqualTo(Integer value) {
            addCriterion("can_loginweb >=", value, "canLoginweb");
            return (Criteria) this;
        }

        public Criteria andCanLoginwebLessThan(Integer value) {
            addCriterion("can_loginweb <", value, "canLoginweb");
            return (Criteria) this;
        }

        public Criteria andCanLoginwebLessThanOrEqualTo(Integer value) {
            addCriterion("can_loginweb <=", value, "canLoginweb");
            return (Criteria) this;
        }

        public Criteria andCanLoginwebIn(List<Integer> values) {
            addCriterion("can_loginweb in", values, "canLoginweb");
            return (Criteria) this;
        }

        public Criteria andCanLoginwebNotIn(List<Integer> values) {
            addCriterion("can_loginweb not in", values, "canLoginweb");
            return (Criteria) this;
        }

        public Criteria andCanLoginwebBetween(Integer value1, Integer value2) {
            addCriterion("can_loginweb between", value1, value2, "canLoginweb");
            return (Criteria) this;
        }

        public Criteria andCanLoginwebNotBetween(Integer value1, Integer value2) {
            addCriterion("can_loginweb not between", value1, value2, "canLoginweb");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andUserDetailIdIsNull() {
            addCriterion("user_detail_id is null");
            return (Criteria) this;
        }

        public Criteria andUserDetailIdIsNotNull() {
            addCriterion("user_detail_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserDetailIdEqualTo(Integer value) {
            addCriterion("user_detail_id =", value, "userDetailId");
            return (Criteria) this;
        }

        public Criteria andUserDetailIdNotEqualTo(Integer value) {
            addCriterion("user_detail_id <>", value, "userDetailId");
            return (Criteria) this;
        }

        public Criteria andUserDetailIdGreaterThan(Integer value) {
            addCriterion("user_detail_id >", value, "userDetailId");
            return (Criteria) this;
        }

        public Criteria andUserDetailIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_detail_id >=", value, "userDetailId");
            return (Criteria) this;
        }

        public Criteria andUserDetailIdLessThan(Integer value) {
            addCriterion("user_detail_id <", value, "userDetailId");
            return (Criteria) this;
        }

        public Criteria andUserDetailIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_detail_id <=", value, "userDetailId");
            return (Criteria) this;
        }

        public Criteria andUserDetailIdIn(List<Integer> values) {
            addCriterion("user_detail_id in", values, "userDetailId");
            return (Criteria) this;
        }

        public Criteria andUserDetailIdNotIn(List<Integer> values) {
            addCriterion("user_detail_id not in", values, "userDetailId");
            return (Criteria) this;
        }

        public Criteria andUserDetailIdBetween(Integer value1, Integer value2) {
            addCriterion("user_detail_id between", value1, value2, "userDetailId");
            return (Criteria) this;
        }

        public Criteria andUserDetailIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_detail_id not between", value1, value2, "userDetailId");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andSmtpServerIsNull() {
            addCriterion("smtp_server is null");
            return (Criteria) this;
        }

        public Criteria andSmtpServerIsNotNull() {
            addCriterion("smtp_server is not null");
            return (Criteria) this;
        }

        public Criteria andSmtpServerEqualTo(String value) {
            addCriterion("smtp_server =", value, "smtpServer");
            return (Criteria) this;
        }

        public Criteria andSmtpServerNotEqualTo(String value) {
            addCriterion("smtp_server <>", value, "smtpServer");
            return (Criteria) this;
        }

        public Criteria andSmtpServerGreaterThan(String value) {
            addCriterion("smtp_server >", value, "smtpServer");
            return (Criteria) this;
        }

        public Criteria andSmtpServerGreaterThanOrEqualTo(String value) {
            addCriterion("smtp_server >=", value, "smtpServer");
            return (Criteria) this;
        }

        public Criteria andSmtpServerLessThan(String value) {
            addCriterion("smtp_server <", value, "smtpServer");
            return (Criteria) this;
        }

        public Criteria andSmtpServerLessThanOrEqualTo(String value) {
            addCriterion("smtp_server <=", value, "smtpServer");
            return (Criteria) this;
        }

        public Criteria andSmtpServerLike(String value) {
            addCriterion("smtp_server like", value, "smtpServer");
            return (Criteria) this;
        }

        public Criteria andSmtpServerNotLike(String value) {
            addCriterion("smtp_server not like", value, "smtpServer");
            return (Criteria) this;
        }

        public Criteria andSmtpServerIn(List<String> values) {
            addCriterion("smtp_server in", values, "smtpServer");
            return (Criteria) this;
        }

        public Criteria andSmtpServerNotIn(List<String> values) {
            addCriterion("smtp_server not in", values, "smtpServer");
            return (Criteria) this;
        }

        public Criteria andSmtpServerBetween(String value1, String value2) {
            addCriterion("smtp_server between", value1, value2, "smtpServer");
            return (Criteria) this;
        }

        public Criteria andSmtpServerNotBetween(String value1, String value2) {
            addCriterion("smtp_server not between", value1, value2, "smtpServer");
            return (Criteria) this;
        }

        public Criteria andBigPictureIsNull() {
            addCriterion("big_picture is null");
            return (Criteria) this;
        }

        public Criteria andBigPictureIsNotNull() {
            addCriterion("big_picture is not null");
            return (Criteria) this;
        }

        public Criteria andBigPictureEqualTo(String value) {
            addCriterion("big_picture =", value, "bigPicture");
            return (Criteria) this;
        }

        public Criteria andBigPictureNotEqualTo(String value) {
            addCriterion("big_picture <>", value, "bigPicture");
            return (Criteria) this;
        }

        public Criteria andBigPictureGreaterThan(String value) {
            addCriterion("big_picture >", value, "bigPicture");
            return (Criteria) this;
        }

        public Criteria andBigPictureGreaterThanOrEqualTo(String value) {
            addCriterion("big_picture >=", value, "bigPicture");
            return (Criteria) this;
        }

        public Criteria andBigPictureLessThan(String value) {
            addCriterion("big_picture <", value, "bigPicture");
            return (Criteria) this;
        }

        public Criteria andBigPictureLessThanOrEqualTo(String value) {
            addCriterion("big_picture <=", value, "bigPicture");
            return (Criteria) this;
        }

        public Criteria andBigPictureLike(String value) {
            addCriterion("big_picture like", value, "bigPicture");
            return (Criteria) this;
        }

        public Criteria andBigPictureNotLike(String value) {
            addCriterion("big_picture not like", value, "bigPicture");
            return (Criteria) this;
        }

        public Criteria andBigPictureIn(List<String> values) {
            addCriterion("big_picture in", values, "bigPicture");
            return (Criteria) this;
        }

        public Criteria andBigPictureNotIn(List<String> values) {
            addCriterion("big_picture not in", values, "bigPicture");
            return (Criteria) this;
        }

        public Criteria andBigPictureBetween(String value1, String value2) {
            addCriterion("big_picture between", value1, value2, "bigPicture");
            return (Criteria) this;
        }

        public Criteria andBigPictureNotBetween(String value1, String value2) {
            addCriterion("big_picture not between", value1, value2, "bigPicture");
            return (Criteria) this;
        }

        public Criteria andSmallPictureIsNull() {
            addCriterion("small_picture is null");
            return (Criteria) this;
        }

        public Criteria andSmallPictureIsNotNull() {
            addCriterion("small_picture is not null");
            return (Criteria) this;
        }

        public Criteria andSmallPictureEqualTo(String value) {
            addCriterion("small_picture =", value, "smallPicture");
            return (Criteria) this;
        }

        public Criteria andSmallPictureNotEqualTo(String value) {
            addCriterion("small_picture <>", value, "smallPicture");
            return (Criteria) this;
        }

        public Criteria andSmallPictureGreaterThan(String value) {
            addCriterion("small_picture >", value, "smallPicture");
            return (Criteria) this;
        }

        public Criteria andSmallPictureGreaterThanOrEqualTo(String value) {
            addCriterion("small_picture >=", value, "smallPicture");
            return (Criteria) this;
        }

        public Criteria andSmallPictureLessThan(String value) {
            addCriterion("small_picture <", value, "smallPicture");
            return (Criteria) this;
        }

        public Criteria andSmallPictureLessThanOrEqualTo(String value) {
            addCriterion("small_picture <=", value, "smallPicture");
            return (Criteria) this;
        }

        public Criteria andSmallPictureLike(String value) {
            addCriterion("small_picture like", value, "smallPicture");
            return (Criteria) this;
        }

        public Criteria andSmallPictureNotLike(String value) {
            addCriterion("small_picture not like", value, "smallPicture");
            return (Criteria) this;
        }

        public Criteria andSmallPictureIn(List<String> values) {
            addCriterion("small_picture in", values, "smallPicture");
            return (Criteria) this;
        }

        public Criteria andSmallPictureNotIn(List<String> values) {
            addCriterion("small_picture not in", values, "smallPicture");
            return (Criteria) this;
        }

        public Criteria andSmallPictureBetween(String value1, String value2) {
            addCriterion("small_picture between", value1, value2, "smallPicture");
            return (Criteria) this;
        }

        public Criteria andSmallPictureNotBetween(String value1, String value2) {
            addCriterion("small_picture not between", value1, value2, "smallPicture");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("creator is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("creator is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(Integer value) {
            addCriterion("creator =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(Integer value) {
            addCriterion("creator <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(Integer value) {
            addCriterion("creator >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(Integer value) {
            addCriterion("creator >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(Integer value) {
            addCriterion("creator <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(Integer value) {
            addCriterion("creator <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<Integer> values) {
            addCriterion("creator in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<Integer> values) {
            addCriterion("creator not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(Integer value1, Integer value2) {
            addCriterion("creator between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(Integer value1, Integer value2) {
            addCriterion("creator not between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andAmenderIsNull() {
            addCriterion("amender is null");
            return (Criteria) this;
        }

        public Criteria andAmenderIsNotNull() {
            addCriterion("amender is not null");
            return (Criteria) this;
        }

        public Criteria andAmenderEqualTo(Integer value) {
            addCriterion("amender =", value, "amender");
            return (Criteria) this;
        }

        public Criteria andAmenderNotEqualTo(Integer value) {
            addCriterion("amender <>", value, "amender");
            return (Criteria) this;
        }

        public Criteria andAmenderGreaterThan(Integer value) {
            addCriterion("amender >", value, "amender");
            return (Criteria) this;
        }

        public Criteria andAmenderGreaterThanOrEqualTo(Integer value) {
            addCriterion("amender >=", value, "amender");
            return (Criteria) this;
        }

        public Criteria andAmenderLessThan(Integer value) {
            addCriterion("amender <", value, "amender");
            return (Criteria) this;
        }

        public Criteria andAmenderLessThanOrEqualTo(Integer value) {
            addCriterion("amender <=", value, "amender");
            return (Criteria) this;
        }

        public Criteria andAmenderIn(List<Integer> values) {
            addCriterion("amender in", values, "amender");
            return (Criteria) this;
        }

        public Criteria andAmenderNotIn(List<Integer> values) {
            addCriterion("amender not in", values, "amender");
            return (Criteria) this;
        }

        public Criteria andAmenderBetween(Integer value1, Integer value2) {
            addCriterion("amender between", value1, value2, "amender");
            return (Criteria) this;
        }

        public Criteria andAmenderNotBetween(Integer value1, Integer value2) {
            addCriterion("amender not between", value1, value2, "amender");
            return (Criteria) this;
        }

        public Criteria andAmendTimeIsNull() {
            addCriterion("amend_time is null");
            return (Criteria) this;
        }

        public Criteria andAmendTimeIsNotNull() {
            addCriterion("amend_time is not null");
            return (Criteria) this;
        }

        public Criteria andAmendTimeEqualTo(Date value) {
            addCriterion("amend_time =", value, "amendTime");
            return (Criteria) this;
        }

        public Criteria andAmendTimeNotEqualTo(Date value) {
            addCriterion("amend_time <>", value, "amendTime");
            return (Criteria) this;
        }

        public Criteria andAmendTimeGreaterThan(Date value) {
            addCriterion("amend_time >", value, "amendTime");
            return (Criteria) this;
        }

        public Criteria andAmendTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("amend_time >=", value, "amendTime");
            return (Criteria) this;
        }

        public Criteria andAmendTimeLessThan(Date value) {
            addCriterion("amend_time <", value, "amendTime");
            return (Criteria) this;
        }

        public Criteria andAmendTimeLessThanOrEqualTo(Date value) {
            addCriterion("amend_time <=", value, "amendTime");
            return (Criteria) this;
        }

        public Criteria andAmendTimeIn(List<Date> values) {
            addCriterion("amend_time in", values, "amendTime");
            return (Criteria) this;
        }

        public Criteria andAmendTimeNotIn(List<Date> values) {
            addCriterion("amend_time not in", values, "amendTime");
            return (Criteria) this;
        }

        public Criteria andAmendTimeBetween(Date value1, Date value2) {
            addCriterion("amend_time between", value1, value2, "amendTime");
            return (Criteria) this;
        }

        public Criteria andAmendTimeNotBetween(Date value1, Date value2) {
            addCriterion("amend_time not between", value1, value2, "amendTime");
            return (Criteria) this;
        }

        public Criteria andAccessGroupIsNull() {
            addCriterion("access_group is null");
            return (Criteria) this;
        }

        public Criteria andAccessGroupIsNotNull() {
            addCriterion("access_group is not null");
            return (Criteria) this;
        }

        public Criteria andAccessGroupEqualTo(Integer value) {
            addCriterion("access_group =", value, "accessGroup");
            return (Criteria) this;
        }

        public Criteria andAccessGroupNotEqualTo(Integer value) {
            addCriterion("access_group <>", value, "accessGroup");
            return (Criteria) this;
        }

        public Criteria andAccessGroupGreaterThan(Integer value) {
            addCriterion("access_group >", value, "accessGroup");
            return (Criteria) this;
        }

        public Criteria andAccessGroupGreaterThanOrEqualTo(Integer value) {
            addCriterion("access_group >=", value, "accessGroup");
            return (Criteria) this;
        }

        public Criteria andAccessGroupLessThan(Integer value) {
            addCriterion("access_group <", value, "accessGroup");
            return (Criteria) this;
        }

        public Criteria andAccessGroupLessThanOrEqualTo(Integer value) {
            addCriterion("access_group <=", value, "accessGroup");
            return (Criteria) this;
        }

        public Criteria andAccessGroupIn(List<Integer> values) {
            addCriterion("access_group in", values, "accessGroup");
            return (Criteria) this;
        }

        public Criteria andAccessGroupNotIn(List<Integer> values) {
            addCriterion("access_group not in", values, "accessGroup");
            return (Criteria) this;
        }

        public Criteria andAccessGroupBetween(Integer value1, Integer value2) {
            addCriterion("access_group between", value1, value2, "accessGroup");
            return (Criteria) this;
        }

        public Criteria andAccessGroupNotBetween(Integer value1, Integer value2) {
            addCriterion("access_group not between", value1, value2, "accessGroup");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIsNull() {
            addCriterion("is_deleted is null");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIsNotNull() {
            addCriterion("is_deleted is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeletedEqualTo(Integer value) {
            addCriterion("is_deleted =", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotEqualTo(Integer value) {
            addCriterion("is_deleted <>", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedGreaterThan(Integer value) {
            addCriterion("is_deleted >", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_deleted >=", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLessThan(Integer value) {
            addCriterion("is_deleted <", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLessThanOrEqualTo(Integer value) {
            addCriterion("is_deleted <=", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIn(List<Integer> values) {
            addCriterion("is_deleted in", values, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotIn(List<Integer> values) {
            addCriterion("is_deleted not in", values, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedBetween(Integer value1, Integer value2) {
            addCriterion("is_deleted between", value1, value2, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotBetween(Integer value1, Integer value2) {
            addCriterion("is_deleted not between", value1, value2, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andUsernameLikeInsensitive(String value) {
            addCriterion("upper(username) like", value.toUpperCase(), "username");
            return (Criteria) this;
        }

        public Criteria andPasswordLikeInsensitive(String value) {
            addCriterion("upper(password) like", value.toUpperCase(), "password");
            return (Criteria) this;
        }

        public Criteria andSignatureLikeInsensitive(String value) {
            addCriterion("upper(signature) like", value.toUpperCase(), "signature");
            return (Criteria) this;
        }

        public Criteria andDefaultLangLikeInsensitive(String value) {
            addCriterion("upper(default_lang) like", value.toUpperCase(), "defaultLang");
            return (Criteria) this;
        }

        public Criteria andStatusLikeInsensitive(String value) {
            addCriterion("upper(status) like", value.toUpperCase(), "status");
            return (Criteria) this;
        }

        public Criteria andTypeLikeInsensitive(String value) {
            addCriterion("upper(type) like", value.toUpperCase(), "type");
            return (Criteria) this;
        }

        public Criteria andSmtpServerLikeInsensitive(String value) {
            addCriterion("upper(smtp_server) like", value.toUpperCase(), "smtpServer");
            return (Criteria) this;
        }

        public Criteria andBigPictureLikeInsensitive(String value) {
            addCriterion("upper(big_picture) like", value.toUpperCase(), "bigPicture");
            return (Criteria) this;
        }

        public Criteria andSmallPictureLikeInsensitive(String value) {
            addCriterion("upper(small_picture) like", value.toUpperCase(), "smallPicture");
            return (Criteria) this;
        }

        public Criteria andDescriptionLikeInsensitive(String value) {
            addCriterion("upper(description) like", value.toUpperCase(), "description");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_user
     *
     * @mbggenerated do_not_delete_during_merge Sat Oct 27 09:26:51 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_user
     *
     * @mbggenerated Sat Oct 27 09:26:51 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}